config/routes.rb
Rails.application.routes.draw do
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  delete 'logout' => 'sessions#destroy'

  resources :sessions, only: [:new, :show]
  resource :balance_sheet, only: [:show]

  get '/', to: 'home#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auth_user.rb
class AuthUser
  include ActiveModel::Model

  attr_accessor(
    :uid,
    :email,
    :first_name,
    :last_name,
    :access_token
  )

  AuthHashError = Class.new(RuntimeError)

  class << self
    def from_omniauth_hash(auth_hash = {})
      raise AuthHashError unless auth_hash[:uid]

      AuthUser.new(
        uid: auth_hash[:uid],
        email: auth_hash[:info][:email],
        first_name: auth_hash[:info][:first_name],
        last_name: auth_hash[:info][:last_name],
        access_token: auth_hash[:info][:access_token]
      )
    end
  end

  def current_auth_token
    access_token['access_token']
  end
end

app/models/balance_sheet.rb
class BalanceSheet
  include ActiveModel::Model

  def initialize(user)
    @user = user
  end

  def retained_profit
    @retained_profit ||=
      fa_client.profit_and_loss_summary['retained_profit_carried_forward'].to_f
  end

  def bank_accounts
    @bank_accounts ||=
      fa_client.bank_accounts.map do |obj|
        OpenStruct.new(
          name: obj['name'],
          current_balance: obj['current_balance'].to_f
        )
      end
  end

  def open_invoices
    @open_invoices ||=
      fa_client.open_invoices.map do |obj|
        OpenStruct.new(
          contact_name: obj['contact_name'],
          due_value: obj['due_value'].to_f
        )
      end
  end

  def corporation_tax_owed
    @corporation_tax_owed ||= trial_balance_total(820)
  end

  def vat_owed
    @vat_owed ||= trial_balance_total(817)
  end

  def adjustments
    [
      bank_accounts.sum(&:current_balance),
      open_invoices.sum(&:due_value),
      corporation_tax_owed,
      vat_owed
    ].inject(0, :+) - retained_profit
  end

  private

  def trial_balance
    @trial_balance ||= fa_client.trial_balance
  end

  def trial_balance_total(nominal_code)
    item = trial_balance.detect { |tb| tb['nominal_code'] == nominal_code.to_s }
    item['total']&.to_f || 0
  end

  def fa_client
    @fa_client ||= FreeagentClient.new(@user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :ensure_fa_user

  def current_user
    AuthUser.new(session[:auth_user])
  end
  helper_method :current_user

  def logged_in?
    session[:auth_user]
  end
  helper_method :logged_in?

  private

  def ensure_fa_user
    logged_in? || redirect_to(new_session_path)
  end
end

app/controllers/balance_sheets_controller.rb
class BalanceSheetsController < ApplicationController
  def show
    @balance_sheet = BalanceSheet.new(current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_fa_user, only: [:new, :create]

  def new; end

  def show
    render json: session[:auth_user]
  end

  def create
    session[:auth_user] =
      AuthUser.from_omniauth_hash(request.env['omniauth.auth'])

    redirect_to '/'
  end

  def destroy
    session[:auth_user] = nil

    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def number_to_gbp(amount, precision = 2)
    number_to_currency(amount, unit: '£', precision: precision)
  end
end

app/views/balance_sheets/_adjustments.html.haml
%tr
  %td
    = link_to "#",
      data: { toggle: 'tooltip' },
      title: 'Includes rounding and items not-displayed.' do
      Adjustments
  %td.text-sm-right.adjustments= number_to_gbp(@balance_sheet.adjustments, 0)

app/views/balance_sheets/show.html.haml
.card.mt-3
  .card-header
    Balance Sheet
  .card-body
    %table.table
      %tbody
        %tr.bg-info.text-white
          %td Assets
          %td

        - @balance_sheet.bank_accounts.each do |bank_account|
          %tr
            %td.bank_account_name
              Bank Account:
              = bank_account.name
            %td.text-sm-right.bank_balance
              = number_to_gbp(bank_account.current_balance, 0)

        - @balance_sheet.open_invoices.each do |open_invoice|
          %tr
            %td.contact_name
              Open Invoice:
              = open_invoice.contact_name
            %td.text-sm-right.due_value
              = number_to_gbp(open_invoice.due_value, 0)

        - if @balance_sheet.adjustments > 0
          = render partial: 'adjustments'

        %tr.bg-warning.text-white
          %td Liabilities
          %td

        %tr#corporation-tax
          %td Corporation Tax owed
          %td.text-sm-right.corporation_tax_owed= number_to_gbp(@balance_sheet.corporation_tax_owed, 0)

        %tr#vat
          %td VAT owed
          %td.text-sm-right.vat_owed= number_to_gbp(@balance_sheet.vat_owed, 0)

        - if @balance_sheet.adjustments < 0
          = render partial: 'adjustments'

        %tr.bg-success.text-white
          %td Owner's Equity
          %td.text-sm-right.retained-profit= number_to_gbp(@balance_sheet.retained_profit, 0)

app/views/home/show.html.haml
.row
  .col-md-6
    %h1 Home
    = link_to "Balance Sheet", balance_sheet_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title HappyHector
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header
      %nav.navbar.navbar-expand-sm.navbar-dark.bg-dark
        %a.navbar-brand{:href => "/"} #{"Happy Hector".upcase}
        %button.navbar-toggler{"data-target" => "#navbarToggler", "data-toggle" => "collapse", :type => "button"}
          %span.navbar-toggler-icon
        #navbarToggler.collapse.navbar-collapse
          = render partial: 'shared/login_out'
    %main
      .container
        = yield

app/views/shared/_login_out.html.haml
%ul.nav.navbar-nav.ml-auto
  - if logged_in?

    %li.nav-item.login-details= link_to current_user.first_name, "#", class: 'nav-link'
    %li.nav-item= link_to 'Sign out', logout_path, method: :delete, class: 'nav-link'
  - else
    %li.nav-item= link_to 'Sign in', '/auth/freeagent_auth/', class: 'nav-link'